"""v02_added_image_field

Revision ID: 1696db78ecb7
Revises: a4c1fef70bf1
Create Date: 2024-07-29 18:26:56.430822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1696db78ecb7'
down_revision: Union[str, None] = 'a4c1fef70bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('story_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'story_image')
    # ### end Alembic commands ###
